
# Configurarea conexiunii la baza de date PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/coworking_db
spring.datasource.username=postgres
spring.datasource.password=targoviste

# Hibernate properties
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Portul pe care ruleaz? serverul (implicit 8080)
server.port=8081